# Generated by Django 3.0.2 on 2021-04-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=50, unique=True, verbose_name='job id')),
                ('project', models.CharField(max_length=255, verbose_name='project')),
                ('spider', models.CharField(max_length=255, verbose_name='spider')),
                ('telnet_username', models.CharField(max_length=50, verbose_name='scrapy telnet username')),
                ('telnet_password', models.CharField(max_length=50, verbose_name='scrapy telnet password')),
                ('telnet_host', models.CharField(max_length=50, verbose_name='scrapy telnet host')),
                ('telnet_port', models.IntegerField(verbose_name='scrapy telnet port')),
                ('close_reason', models.CharField(default=None, max_length=50, null=True, verbose_name='close reason')),
                ('status', models.IntegerField(choices=[(1, 'Running'), (2, 'Closed')], default=1, verbose_name="status: [(1, 'Running'), (2, 'Closed')]")),
                ('log_file', models.CharField(max_length=255, null=True, verbose_name='log file path')),
                ('job_start_time', models.DateTimeField(default=None, null=True, verbose_name='job start time')),
                ('job_end_time', models.DateTimeField(default=None, null=True, verbose_name='job end time')),
                ('stats', models.TextField(default='{}', verbose_name='stat info')),
                ('settings', models.TextField(default='{}', verbose_name='settings info')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'spider_job',
                'index_together': {('project', 'spider')},
            },
        ),
    ]
