# Generated by Django 3.0.2 on 2020-03-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spiderjob',
            old_name='stat_info',
            new_name='stats',
        ),
        migrations.AddField(
            model_name='spiderjob',
            name='settings',
            field=models.TextField(default='{}', verbose_name='settings info'),
        ),
    ]
